#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jun 12 09:58:00 PDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
